name: dt_test
description: "Habit tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-81.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  dio: ^5.3.3
  connectivity_plus: ^5.0.1
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  get_it: ^7.6.4
  auto_route: ^7.8.4
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4
  talker_flutter: ^3.5.4
  talker_dio_logger: ^2.3.1
  talker_bloc_logger: ^2.2.1
  flutter_colorpicker: ^1.0.3
  collection: ^1.18.0
  mockito: ^5.4.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2
  build_runner:

flutter:
  uses-material-design: true

